meuprog: meuprog.o fila.o etc.o
	gcc meuprog.o fila.o etc.o -o meuprog ;
meuprog.o: meuprog.c minhasdefs.h fila.h etc.h
	gcc -c meuprog.c;
fila.o: fila.c minhasdefs.h fila.h
	gcc -c fila.c;
etc.o: etc.c minhasdefs.h etc.h
	gcc -c etc.c;
